"""initial schema

Revision ID: 8d37f7b66f3c
Revises: 
Create Date: 2026-07-09 04:57:35.715586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '8d37f7b66f3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('product_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scrape_frequency', sa.String(length=20), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sources_product_id'), 'product_sources', ['product_id'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_text_excerpt', sa.Text(), nullable=True),
    sa.Column('artifact_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['product_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_runs_product_id'), 'scrape_runs', ['product_id'], unique=False)
    op.create_index(op.f('ix_scrape_runs_source_id'), 'scrape_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_scrape_runs_status'), 'scrape_runs', ['status'], unique=False)
    op.create_table('label_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_hash', sa.String(length=64), nullable=False),
    sa.Column('effective_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('original_image_paths', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('structured_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['product_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_versions_product_id'), 'label_versions', ['product_id'], unique=False)
    op.create_index(op.f('ix_label_versions_version_hash'), 'label_versions', ['version_hash'], unique=False)
    op.create_table('allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_version_id', sa.Integer(), nullable=False),
    sa.Column('allergen_name', sa.String(length=100), nullable=False),
    sa.Column('presence_type', sa.String(length=30), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['label_version_id'], ['label_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergens_allergen_name'), 'allergens', ['allergen_name'], unique=False)
    op.create_index(op.f('ix_allergens_label_version_id'), 'allergens', ['label_version_id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_version_id', sa.Integer(), nullable=False),
    sa.Column('certification_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['label_version_id'], ['label_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_certification_name'), 'certifications', ['certification_name'], unique=False)
    op.create_index(op.f('ix_certifications_label_version_id'), 'certifications', ['label_version_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_version_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name_raw', sa.String(length=300), nullable=False),
    sa.Column('ingredient_name_normalized', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_additive', sa.Boolean(), nullable=False),
    sa.Column('is_sweetener', sa.Boolean(), nullable=False),
    sa.Column('is_preservative', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['label_version_id'], ['label_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_ingredient_name_normalized'), 'ingredients', ['ingredient_name_normalized'], unique=False)
    op.create_index(op.f('ix_ingredients_label_version_id'), 'ingredients', ['label_version_id'], unique=False)
    op.create_table('label_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_version_id', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.String(length=500), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=True),
    sa.Column('normalized_claim', sa.String(length=200), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['label_version_id'], ['label_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_claims_label_version_id'), 'label_claims', ['label_version_id'], unique=False)
    op.create_index(op.f('ix_label_claims_normalized_claim'), 'label_claims', ['normalized_claim'], unique=False)
    op.create_table('label_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('old_label_version_id', sa.Integer(), nullable=False),
    sa.Column('new_label_version_id', sa.Integer(), nullable=False),
    sa.Column('diff_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('significance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['new_label_version_id'], ['label_versions.id'], ),
    sa.ForeignKeyConstraint(['old_label_version_id'], ['label_versions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_comparisons_product_id'), 'label_comparisons', ['product_id'], unique=False)
    op.create_index(op.f('ix_label_comparisons_significance_score'), 'label_comparisons', ['significance_score'], unique=False)
    op.create_table('nutrition_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_version_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('per_serving_or_100g', sa.String(length=20), nullable=False),
    sa.Column('daily_value_percent', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['label_version_id'], ['label_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_items_label_version_id'), 'nutrition_items', ['label_version_id'], unique=False)
    op.create_index(op.f('ix_nutrition_items_nutrient_name'), 'nutrition_items', ['nutrient_name'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=True),
    sa.Column('label_version_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('analysis_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('plain_english_summary', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['label_comparisons.id'], ),
    sa.ForeignKeyConstraint(['label_version_id'], ['label_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_analysis_type'), 'ai_analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_ai_analyses_comparison_id'), 'ai_analyses', ['comparison_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_label_version_id'), 'ai_analyses', ['label_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analyses_label_version_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_comparison_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_analysis_type'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_nutrition_items_nutrient_name'), table_name='nutrition_items')
    op.drop_index(op.f('ix_nutrition_items_label_version_id'), table_name='nutrition_items')
    op.drop_table('nutrition_items')
    op.drop_index(op.f('ix_label_comparisons_significance_score'), table_name='label_comparisons')
    op.drop_index(op.f('ix_label_comparisons_product_id'), table_name='label_comparisons')
    op.drop_table('label_comparisons')
    op.drop_index(op.f('ix_label_claims_normalized_claim'), table_name='label_claims')
    op.drop_index(op.f('ix_label_claims_label_version_id'), table_name='label_claims')
    op.drop_table('label_claims')
    op.drop_index(op.f('ix_ingredients_label_version_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_ingredient_name_normalized'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_certifications_label_version_id'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_certification_name'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_allergens_label_version_id'), table_name='allergens')
    op.drop_index(op.f('ix_allergens_allergen_name'), table_name='allergens')
    op.drop_table('allergens')
    op.drop_index(op.f('ix_label_versions_version_hash'), table_name='label_versions')
    op.drop_index(op.f('ix_label_versions_product_id'), table_name='label_versions')
    op.drop_table('label_versions')
    op.drop_index(op.f('ix_scrape_runs_status'), table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_source_id'), table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_product_id'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index(op.f('ix_product_sources_product_id'), table_name='product_sources')
    op.drop_table('product_sources')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
